language: ruby
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci:metrics"
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx
matrix:
  include:
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"  # for simplecov
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"  # for simplecov
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
